Libreria-app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LibroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('libro',LibroController::class);

Libreria-app/app/Models/Editorial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Editorial extends Model
{
    use HasFactory;
    protected $fillable=['nombre'];
    public function libros() {
        return $this->hasMany(Libro::class,'editorial_id' , 'id');
    }
}

Libreria-app/app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    use HasFactory;
    protected $fillable = [
        'titulo',
        'editorial_id',
        'edicion',
        'pais',
        'precio'
    ];
    public function editorial()
    {
        return $this->belongsTo(Editorial::class,'editorial_id' , 'id');
    }
}

Libreria-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

Libreria-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Libreria-app/app/Http/Controllers/EditorialController.php
<?php

namespace App\Http\Controllers;

use App\Models\Editorial;
use Illuminate\Http\Request;

class EditorialController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Editorial $editorial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Editorial $editorial)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Editorial $editorial)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Editorial $editorial)
    {
        //
    }
}

Libreria-app/app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Libro;
use Illuminate\Http\Request;
use App\Models\Editorial;
class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $libros = Libro::all();
        return view('libro.index', [
            'libros' => $libros
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view ('libro.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input = $request->all();
        Libro::create($input);
        return redirect()-route('libro.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Libro $libro)
    {
        
        return view('libro.show',[
            'libro' => $libro
        ]);

    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Libro $libro)
    {
        return view('libro.edit',[
            'libro' => $libro
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Libro $libro)
    {
        $input = $request->all();
        $libro->update($input);
        return view('libro.show',[
            'libro' => $libro
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Libro $libro)
    {
        $libro->delete();
        return redirect()->route('libro.index');
    }
}

Libreria-app/resources/views/libro/index.blade.php
@extends('layouts.app')

@section('content')
<h1 class="text-3xl text-center text-blue-500 mt-4">Listado de clientes</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full text-center text-sm font-light">
            <thead class="border-b font-medium dark:border-neutral-500">
            <tr class="bg-blue-500 text-xl text-white">
                <th scope="col" class="px-6 py-4">Titulo</th>
                <th scope="col" class="px-6 py-4">Editorial</th>
                <th scope="col" class="px-6 py-4">Edicion</th>    
                <th scope="col" class="px-6 py-4">Pais</th>
                <th scope="col" class="px-6 py-4">Precio</th>
                <th scope="col" class="px-6 py-4">Acciones</th>

              </tr>
            </thead>
            <tbody>
                @foreach ($libros as $libro)
                <tr class="border-b dark:border-neutral-500">
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->titulo}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->editorial->nombre}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->edicion}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->pais}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->precio}}</td>
                    <td class="whitespace-nowrap px-6 py-4">
                        <a href="{{route('libro.show',$libro->id)}}"class="bg-blue-500 text-white px-2 py-1 rounded-md mr-2">Mostrar</a>
                        <a href="{{route('libro.edit',$libro->id)}}"class="bg-yellow-500 text-white px-2 py-1 rounded-md mr-2">Editar</a>
                    
                        <form action="{{route('libro.destroy',$libro->id)}}" method="post" class="inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit"class="bg-red-500 text-white px-2 py-1 rounded-md mr-2">Eliminar</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


<a href="{{route('libro.create')}}"class="bg-green-500 text-white px-2 py-1 rounded-md">Registrar Cliente</a>
@endsection